on:
  push:
    branches:
      - main

jobs:
  build:
    name: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Create & Publish Container
        run: |
          gcloud auth configure-docker
          ./gradlew :server:bootBuildImage --imageName=gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.event.repository.name }}:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Deploy Service and DB
        uses: jamesward/easycloudrun/vpcsql@main
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: ${{ secrets.GCP_REGION }}
          DB_VERSION: POSTGRES_13
          DB_TIER: db-f1-micro
          DB_INIT_ARGS: init --spring.main.web-application-type=none

      - name: Create Static Site
        run: |
          ./gradlew :web:jsBrowserDistribution

      - name: Deploy Static
        uses: jamesward/easycloudrun/staticandapi@main
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: ${{ secrets.GCP_REGION }}
          DOMAINS: ${{ secrets.DOMAINS }}
          FILE_PATH: web/build/distributions
          API_PATH: /api
