on: push

jobs:
  build:
    name: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('build.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create & Publish Container
        run: |
          gcloud auth configure-docker
          ./gradlew :server:bootBuildImage --imageName=gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.event.repository.name }}:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Deploy
        uses: jamesward/easycloudrun/deploy@main
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: ${{ secrets.GCP_REGION }}