on: push
#  push:
#    tags:
#      - "v*"

jobs:

  build:
    name: build
    runs-on: macos-12

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: import certs
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: Install provisioning profile
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

#      - name: download dev provisioning profiles
#        uses: apple-actions/download-provisioning-profiles@v1
#        with:
#          profile-type: 'IOS_APP_DEVELOPMENT'
#          bundle-id: ${{ secrets.ASC_BUNDLE_ID }}
#          issuer-id: ${{ secrets.ASC_API_ISSUER }}
#          api-key-id: ${{ secrets.ASC_API_KEY }}
#          api-private-key: ${{ secrets.ASC_AUTH_KEY }}
#
#      - name: download dist provisioning profiles
#        uses: apple-actions/download-provisioning-profiles@v1
#        with:
#          profile-type: 'IOS_APP_STORE'
#          bundle-id: ${{ secrets.ASC_BUNDLE_ID }}
#          issuer-id: ${{ secrets.ASC_API_ISSUER }}
#          api-key-id: ${{ secrets.ASC_API_KEY }}
#          api-private-key: ${{ secrets.ASC_AUTH_KEY }}

      - name: create archive
        working-directory: iosApp
        run: |
          
          cat <<EOF > ../local.properties
          barsUrl=https://${{ secrets.DOMAINS }}/api/bars
          EOF
          
          # todo: this is duplicated in the build phase run script
          #       because for some reason the file needs to be there before we run xcodebuild
          cat <<EOF > Kotlin-Bars-Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>BarsUrl</key>
              <string>https://${{ secrets.DOMAINS }}/api/bars</string>
            </dict>
          </plist>
          EOF
          
          if [ "${{ github.ref_type }}" = "tag" ]; then
            agvtool new-marketing-version ${GITHUB_REF_NAME#v}
          fi
          
          xcrun agvtool new-version -all ${GITHUB_RUN_NUMBER}
        
          xcrun xcodebuild -scheme Kotlin_Bars -sdk iphoneos -configuration Release -destination 'generic/platform=iOS' -archivePath build/Kotlin_Bars.xcarchive archive

      - name: export archive
        working-directory: iosApp
        run: |

          cat <<EOF > build/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>generateAppStoreInformation</key>
              <false/>
              <key>manageAppVersionAndBuildNumber</key>
              <true/>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string>${{ secrets.ASC_TEAM_ID }}</string>
              <key>uploadBitcode</key>
              <true/>
              <key>uploadSymbols</key>
              <true/>
            </dict>
          </plist>
          EOF

          xcrun xcodebuild -exportArchive -archivePath build/Kotlin_Bars.xcarchive -exportOptionsPlist build/ExportOptions.plist -exportPath build

      - name: upload ipa
        uses: actions/upload-artifact@v2
        with:
          name: kotlin-bars.ipa
          path: iosApp/build/Kotlin_Bars.ipa

      - name: release ipa
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: kotlin-bars.ipa
          file: iosApp/build/Kotlin_Bars.ipa
          tag: ${{ github.ref }}
          overwrite: true

      - name: upload app to testflight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: iosApp/build/Kotlin_Bars.ipa
          issuer-id: ${{ secrets.ASC_API_ISSUER }}
          api-key-id: ${{ secrets.ASC_API_KEY }}
          api-private-key: ${{ secrets.ASC_AUTH_KEY }}
